# Generated by Django 3.2.6 on 2022-02-12 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('country', models.CharField(default=None, max_length=255, null=True)),
                ('postcode', models.CharField(default=None, max_length=16, null=True)),
                ('lat', models.FloatField(default=0, null=True)),
                ('lng', models.FloatField(default=0, null=True)),
                ('is_place_of_birth_address', models.BooleanField(default=False)),
                ('is_domicile', models.BooleanField(default=False)),
                ('is_temporary_residence_address', models.BooleanField(default=False)),
                ('is_permanent_address', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
