# Generated by Django 3.2.6 on 2022-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='commune',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
