# Generated by Django 3.2.6 on 2022-02-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20220213_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_head_office_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_working_office_address',
            field=models.BooleanField(default=False),
        ),
    ]
