# Generated by Django 3.2.6 on 2022-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20220219_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
