# Generated by Django 3.2.6 on 2022-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_is_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_customer_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_domicile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_head_office_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_permanent_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_place_of_birth_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_temporary_residence_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_working_office_address',
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, default='place_of_birth_address', max_length=255, null=True),
        ),
    ]
