# Generated by Django 3.2.6 on 2022-02-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_notification_on',
        ),
    ]
