# Generated by Django 3.2.6 on 2022-03-05 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_notification_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFCMDevice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('type', models.CharField(choices=[('P', 'PORTAL'), ('M', 'MOBILE')], default='M', max_length=50)),
                ('device', models.CharField(choices=[('A', 'ANDROID'), ('I', 'IOS'), ('B', 'BROWSER')], max_length=200, null=True)),
                ('user_type', models.CharField(max_length=200, null=True)),
                ('meid', models.CharField(max_length=200, null=True)),
                ('token', models.TextField()),
                ('user', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.expressions.Case, related_name='UserFCMDevices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
