# Generated by Django 3.2.6 on 2022-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmdevice',
            name='type',
            field=models.CharField(choices=[('P', 'PORTAL'), ('M', 'MOBILE')], max_length=50, null=True),
        ),
    ]
