# Generated by Django 3.2.6 on 2023-01-14 20:51

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220506_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', base.models.AbstractUserManager()),
            ],
        ),
    ]
