# Generated by Django 3.2.6 on 2023-01-15 04:31

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminStaff',
        ),
        migrations.CreateModel(
            name='HrUserAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Hr User',
                'verbose_name_plural': 'Hr User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', base.models.AbstractUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
