# Generated by Django 3.2.6 on 2022-03-16 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0006_rename_address_staffs_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffYears',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 16, 14, 25, 54, 993109, tzinfo=utc))),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('contact', models.TextField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_staff', to='staffs.staffs')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_off_year_staff', to='staffs.staffs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
