# Generated by Django 3.2.6 on 2022-03-16 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0003_alter_dayoffyears_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoffyears',
            name='hand_over',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dayoffyears',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 16, 15, 49, 11, 264090, tzinfo=utc)),
        ),
    ]
