# Generated by Django 3.2.6 on 2022-03-25 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0004_auto_20220316_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyears',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 1, 48, 40, 232760, tzinfo=utc)),
        ),
    ]
