# Generated by Django 3.2.6 on 2022-03-25 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0007_alter_dayoffyears_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyears',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 3, 15, 34, 452396, tzinfo=utc)),
        ),
    ]
