# Generated by Django 3.2.6 on 2022-03-25 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0009_alter_dayoffyears_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyears',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 4, 20, 44, 207010, tzinfo=utc)),
        ),
    ]
