# Generated by Django 3.2.6 on 2022-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0012_alter_dayoffyears_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyears',
            name='date',
            field=models.DateField(),
        ),
    ]
