# Generated by Django 3.2.6 on 2022-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_years', '0013_alter_dayoffyears_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoffyears',
            name='is_print',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dayoffyears',
            name='link_day_off_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
