# Generated by Django 3.2.6 on 2022-03-16 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('day_off_years', '0002_alter_dayoffyears_date'),
        ('day_off_types', '0002_dayofftypes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffYearDetails',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('from_date', models.DateField(default=datetime.datetime(2022, 3, 16, 14, 31, 0, 794222, tzinfo=utc))),
                ('to_date', models.DateField(default=datetime.datetime(2022, 3, 16, 14, 31, 0, 794222, tzinfo=utc))),
                ('amount', models.FloatField(default=1.0)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('day_off_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_off_type_day_off_year_detail', to='day_off_types.dayofftypes')),
                ('day_off_years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_off_year_day_off_year_detail', to='day_off_years.dayoffyears')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
