# Generated by Django 3.2.6 on 2022-03-16 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_year_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoffyeardetails',
            name='status',
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 16, 15, 36, 16, 579853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 16, 15, 36, 16, 579853, tzinfo=utc)),
        ),
    ]
