# Generated by Django 3.2.6 on 2022-03-25 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_year_details', '0007_auto_20220325_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 4, 19, 29, 164618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 4, 19, 29, 164639, tzinfo=utc)),
        ),
    ]
