# Generated by Django 3.2.6 on 2022-03-27 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_year_details', '0009_auto_20220325_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 1, 49, 39, 109312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 1, 49, 39, 109344, tzinfo=utc)),
        ),
    ]
