# Generated by Django 3.2.6 on 2022-03-27 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_year_details', '0010_auto_20220327_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 2, 46, 39, 91144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 2, 46, 39, 91166, tzinfo=utc)),
        ),
    ]
