# Generated by Django 3.2.6 on 2022-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_off_year_details', '0011_auto_20220327_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dayoffyeardetails',
            name='to_date',
            field=models.DateField(),
        ),
    ]
