# Generated by Django 3.2.6 on 2022-03-03 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customers_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('project', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('service', models.CharField(default=None, max_length=255)),
                ('contract_number', models.CharField(default=None, max_length=255)),
                ('signing_date', models.DateField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('finish_date', models.DateField(default=None)),
                ('status', models.BooleanField(default=1)),
                ('size', models.CharField(default=None, max_length=255)),
                ('image', models.CharField(default=None, max_length=255)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('file', models.CharField(default=None, max_length=255)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_customer', to='customers.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
