# Generated by Django 3.2.6 on 2022-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
