# Generated by Django 3.2.6 on 2022-03-30 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_rename_departments_departments_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRequirement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('created_at_recruitment', models.DateField()),
                ('approved_by', models.CharField(default=None, max_length=255)),
                ('asked_by', models.CharField(default=None, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requirements_department', to='departments.departments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
