# Generated by Django 3.2.6 on 2022-03-30 03:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainningRequirement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('date_requirement', models.DateField()),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('course_name', models.CharField(default=None, max_length=255)),
                ('organizational_units', models.CharField(default=None, max_length=255)),
                ('time_organizational', models.DateField()),
                ('estimated_cost', models.FloatField()),
                ('place', models.CharField(default=None, max_length=255)),
                ('sign_by', models.CharField(default=None, max_length=255)),
                ('unit_head', models.CharField(default=None, max_length=255)),
                ('approved_by', models.CharField(default=None, max_length=255)),
                ('unit', models.CharField(default=None, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainning_requirements_branch', to='branchs.branchs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
