# Generated by Django 3.2.6 on 2022-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainning_requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainningrequirement',
            name='approved_by',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='course_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='date_requirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='organizational_units',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='sign_by',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='time_organizational',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainningrequirement',
            name='unit_head',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
