# Generated by Django 3.2.6 on 2022-03-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_auto_20220327_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='actual_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='standard_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True),
        ),
    ]
