# Generated by Django 3.2.6 on 2022-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_auto_20220327_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
