# Generated by Django 3.2.6 on 2022-03-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0004_alter_salary_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
