# Generated by Django 3.2.6 on 2022-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0008_auto_20220327_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
