# Generated by Django 3.2.6 on 2022-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0009_auto_20220327_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='is_print',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='link_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
