# Generated by Django 3.2.6 on 2022-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0010_auto_20220504_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='link_list_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
