# Generated by Django 3.2.6 on 2022-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0011_salary_link_list_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='link_list_department_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
