# Generated by Django 3.2.6 on 2022-03-27 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kinds_of_work', '0001_initial'),
        ('staffs', '0006_rename_address_staffs_addresses'),
        ('projects', '0002_alter_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timekeeping',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('date', models.DateField()),
                ('amount_in_project', models.FloatField(default=1)),
                ('amount_time', models.FloatField(default=0)),
                ('note', models.TextField(default=None)),
                ('type', models.CharField(default=0.1, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_project', to='projects.projects')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_staff', to='staffs.staffs')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_work', to='kinds_of_work.kindsofwork')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
