# Generated by Django 3.2.6 on 2022-03-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='type',
            field=models.FloatField(default=0.1),
        ),
    ]
