# Generated by Django 3.2.6 on 2022-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0002_alter_timekeeping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='type',
            field=models.FloatField(default=1),
        ),
    ]
