# Generated by Django 3.2.6 on 2022-03-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_project', '0001_initial'),
        ('timekeeping', '0003_alter_timekeeping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timekeeping',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='staff',
        ),
        migrations.AddField(
            model_name='timekeeping',
            name='staff_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_staff_project', to='staff_project.staffproject'),
        ),
    ]
