# Generated by Django 3.2.6 on 2022-03-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_project', '0001_initial'),
        ('timekeeping', '0006_alter_timekeeping_staff_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='staff_project',
            field=models.ForeignKey(blank=True, default='ec8043b8-aff1-4a49-9f10-c5c52fa685fd', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_staff_project', to='staff_project.staffproject'),
        ),
    ]
