# Generated by Django 3.2.6 on 2022-03-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_project', '0001_initial'),
        ('timekeeping', '0008_alter_timekeeping_staff_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='staff_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_staff_project', to='staff_project.staffproject'),
        ),
    ]
