# Generated by Django 3.2.6 on 2022-04-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0009_alter_timekeeping_staff_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='amount_in_project',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='amount_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
