# Generated by Django 3.2.6 on 2022-05-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinds_of_work', '0001_initial'),
        ('timekeeping', '0010_auto_20220428_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='type_work',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeeping_work', to='kinds_of_work.kindsofwork'),
        ),
    ]
