# Generated by Django 3.2.6 on 2022-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetypes',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
