# Generated by Django 3.2.6 on 2022-03-25 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0006_rename_address_staffs_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('content', models.TextField(default=None)),
                ('date', models.DateField()),
                ('expire', models.DateField()),
                ('attach', models.CharField(default=None, max_length=255)),
                ('note', models.CharField(default=None, max_length=255)),
                ('form_of_discipline', models.CharField(default=None, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_staff', to='staffs.staffs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
