# Generated by Django 3.2.6 on 2022-03-13 04:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('literacy', '0001_initial'),
        ('nationalities', '0001_initial'),
        ('addresses', '0006_auto_20220312_2319'),
        ('departments', '0003_rename_departments_departments_department'),
        ('religions', '0001_initial'),
        ('ethnicities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('staff', models.CharField(default=None, max_length=255)),
                ('gender', models.CharField(default='unknown', max_length=255)),
                ('marital_status', models.CharField(default='single', max_length=255)),
                ('number_of_children', models.IntegerField(blank=True, default=0, null=True)),
                ('identity_card', models.CharField(default=None, max_length=255, unique=True)),
                ('issuance_date', models.DateField(blank=True, default=None, null=True)),
                ('place_of_issuance', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_work_date', models.DateField(blank=True, default=None, null=True)),
                ('probationary_end_date', models.DateField(blank=True, default=None, null=True)),
                ('labor_contract_signing_date', models.DateField(blank=True, default=None, null=True)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('personal_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('social_insurance_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bank_account', models.IntegerField(blank=True, default=None, null=True)),
                ('elect_notifications', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('addresses', models.ManyToManyField(default=None, null=True, related_name='staff_addresses', to='addresses.Address')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_department', to='departments.departments')),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_ethnicities', to='ethnicities.ethnicities')),
                ('literacy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_literacy', to='literacy.literacy')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_nationalities', to='nationalities.nationalities')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_religions', to='religions.religions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
