# Generated by Django 3.2.6 on 2022-03-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_staffs_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='addresses',
            new_name='address',
        ),
    ]
