# Generated by Django 3.2.6 on 2022-03-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_rename_addresses_staffs_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='address',
            new_name='addresses',
        ),
    ]
