# Generated by Django 3.2.6 on 2022-04-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
        ('staffs', '0008_alter_staffs_identity_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_position', to='positions.positions'),
        ),
    ]
