# Generated by Django 3.2.6 on 2022-05-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_staffs_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='is_print',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='link_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
