# Generated by Django 3.2.6 on 2022-05-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_auto_20220505_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='link_salary',
            new_name='link_staff',
        ),
    ]
