# Generated by Django 3.2.6 on 2022-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_rename_link_salary_staffs_link_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='link_all_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
