# Generated by Django 3.2.6 on 2022-03-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='level',
        ),
    ]
