# Generated by Django 3.2.6 on 2022-03-03 08:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0005_address_is_customer_address'),
        ('companies', '0006_companies_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('website', models.CharField(default=None, max_length=255)),
                ('file', models.CharField(default=None, max_length=255)),
                ('addresses', models.ManyToManyField(default=None, null=True, related_name='customer_addresses', to='addresses.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_company', to='companies.companies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
