# Generated by Django 3.2.6 on 2022-03-30 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment_requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRequirementDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('time_to_finish', models.DateField()),
                ('content', models.TextField(default=None)),
                ('position_requirement', models.CharField(default=None, max_length=255)),
                ('amount', models.IntegerField()),
                ('recuitment_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requirements_detail_recruitment_requirements', to='recruitment_requirements.recruitmentrequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
