# Generated by Django 3.2.6 on 2022-02-19 12:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0003_auto_20220219_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('company', models.CharField(max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('tax_code', models.CharField(default=None, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('website', models.CharField(default=None, max_length=255)),
                ('fax', models.CharField(default=None, max_length=255)),
                ('logo', models.CharField(default=None, max_length=255)),
                ('head_office_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_head_office_address', to='addresses.address')),
                ('working_office_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_working_office_address', to='addresses.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
