# Generated by Django 3.2.6 on 2022-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20220219_1920'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='head_office_address',
        ),
        migrations.AddField(
            model_name='companies',
            name='head_office_address',
            field=models.ManyToManyField(default=None, null=True, related_name='company_head_office_address', to='addresses.Address'),
        ),
        migrations.RemoveField(
            model_name='companies',
            name='working_office_address',
        ),
        migrations.AddField(
            model_name='companies',
            name='working_office_address',
            field=models.ManyToManyField(default=None, null=True, related_name='company_working_office_address', to='addresses.Address'),
        ),
    ]
