# Generated by Django 3.2.6 on 2022-02-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20220219_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='working_office_address',
            new_name='addresses',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='head_office_address',
        ),
    ]
