# Generated by Django 3.2.6 on 2022-02-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companies_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='addresses',
        ),
    ]
