# Generated by Django 3.2.6 on 2022-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_province'),
        ('companies', '0005_remove_companies_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='addresses',
            field=models.ManyToManyField(default=None, null=True, related_name='company_addresses', to='addresses.Address'),
        ),
    ]
