# Generated by Django 3.2.6 on 2022-03-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branchs',
            new_name='Departments',
        ),
    ]
