# Generated by Django 3.2.6 on 2022-03-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_branchs_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='departments',
            new_name='department',
        ),
    ]
