# Generated by Django 3.2.6 on 2022-03-30 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment_requirement_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentTracking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('position_recruiment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_receive_receipt_of_application', models.DateField()),
                ('is_job_application', models.BooleanField(default=False)),
                ('is_cv', models.BooleanField(default=False)),
                ('is_diploma', models.BooleanField(default=False)),
                ('is_health_certification', models.BooleanField(default=False)),
                ('office_day01', models.DateField()),
                ('is_qualification01', models.BooleanField(default=False)),
                ('office_day02', models.DateField()),
                ('is_qualification02', models.BooleanField(default=False)),
                ('is_agree_recruiment', models.BooleanField(default=False)),
                ('contact_before_sign_contract', models.CharField(default=None, max_length=255)),
                ('date_start_work', models.DateField()),
                ('salary_start', models.FloatField()),
                ('is_receive_recruing_decision', models.BooleanField(default=False)),
                ('date_receive_recruing_decision', models.DateField()),
                ('recruitment_requirement_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requirement_detail_recruitment_tracking', to='recruitment_requirement_details.recruitmentrequirementdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
